In [1]:
import os
import sys
import copy
import importlib
import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.realpath(os.path.join(os.path.dirname(os.getcwd()))))
sys.path.append(SCRIPT_DIR)

import gwfast.gwfastGlobals as glob
import gwfast.waveforms as waveforms
import gwfast.signal as signal
import gwfast.network as network
import gwfast.fisherTools as fTools

LSC Algorithm Library (LAL) is not installed, only the GWFAST waveform models are available, namely: TaylorF2, IMRPhenomD, IMRPhenomD_NRTidalv2, IMRPhenomHM and IMRPhenomNSBH
TEOBResumS is not installed, only the GWFAST waveform models are available, namely: TaylorF2, IMRPhenomD, IMRPhenomD_NRTidalv2, IMRPhenomHM and IMRPhenomNSBH


In [2]:
# importlib.reload(signal)

In [5]:
events = {
    'Mc':np.array([50]), 'eta':np.array([0.24]), 'dL':np.array([0.8]), 'theta':np.array([2.34]), 'phi':np.array([5.43]), 
    'iota':np.array([0.9 * np.pi/2]), 'psi':np.array([1]), 'tGPS':np.array([0]), 'Phicoal':np.array([2.8]), 
    'chi1z':np.array([1e-3]), 'chi2z':np.array([1e-3]), 'chi1x':np.array([0]), 'chi2x':np.array([0]), 'chi1y':np.array([0]), 'chi2y':np.array([0]), 
    'LambdaTilde':np.array([0]), 'deltaLambda':np.array([0]), 'ecc':np.array([0]), 
    'phi_L':np.array([0.9*np.pi/2]), 'R_orbit':np.array([200])
}

mywf = waveforms.TaylorF2_RestrictedPN()

In [6]:
L1_conf = copy.deepcopy(glob.detectors).pop('L1')
L1_conf['psd_path'] = os.path.join(glob.detPath, 'observing_scenarios_paper', 'AplusDesign.txt')

H1_conf = copy.deepcopy(glob.detectors).pop('H1')
H1_conf['psd_path'] = os.path.join(glob.detPath, 'observing_scenarios_paper', 'AplusDesign.txt')

Virgo_conf = copy.deepcopy(glob.detectors).pop('Virgo')
Virgo_conf['psd_path'] =  os.path.join(glob.detPath, 'observing_scenarios_paper', 'avirgo_O5low_NEW.txt')

# Initialise the GWSignal objects
L1 = signal.GWSignal(mywf, psd_path=L1_conf['psd_path'], 
                        detector_shape=L1_conf['shape'], det_lat=L1_conf['lat'], 
                        det_long=L1_conf['long'], det_xax=L1_conf['xax'],
                        fmin=10
                        )
H1 = signal.GWSignal(mywf, psd_path=H1_conf['psd_path'], 
                        detector_shape=H1_conf['shape'], det_lat=H1_conf['lat'], 
                        det_long=H1_conf['long'], det_xax=H1_conf['xax'],
                        fmin=10
                        )
Virgo = signal.GWSignal(mywf, psd_path=Virgo_conf['psd_path'], 
                        detector_shape=Virgo_conf['shape'], det_lat=Virgo_conf['lat'], 
                        det_long=Virgo_conf['long'], det_xax=Virgo_conf['xax'],
                        fmin=10
                        )

mySignals = {'L1':L1, 'H1':H1, 'Virgo':Virgo}
myNet = network.DetNet(mySignals)

Using ASD from file /Users/yuranzhang/gwfast_AGN/gwfast_moddd/psds/observing_scenarios_paper/AplusDesign.txt 
Initializing jax...
Jax local device count: 8
Jax  device count: 8
Using ASD from file /Users/yuranzhang/gwfast_AGN/gwfast_moddd/psds/observing_scenarios_paper/AplusDesign.txt 
Initializing jax...
Jax local device count: 8
Jax  device count: 8
Using ASD from file /Users/yuranzhang/gwfast_AGN/gwfast_moddd/psds/observing_scenarios_paper/avirgo_O5low_NEW.txt 
Initializing jax...
Jax local device count: 8
Jax  device count: 8


In [7]:
mySNR = myNet.SNR(events, use_lensing=True, return_all=True)
mySNR_nolens = myNet.SNR(events, return_all=True)
print("SNR with lensing:", mySNR)
print("SNR without lensing:", mySNR_nolens)

Adding tcoal from tGPS
[[ 7.85737726e-24+1.47867376e-23j]
 [ 1.63280540e-23+3.59429096e-24j]
 [-8.46874900e-24+1.43856005e-23j]
 [ 1.49248485e-23+7.42008663e-24j]
 [-1.37135643e-25+1.66413999e-23j]
 [ 1.12910658e-23-1.21908024e-23j]
 [ 1.48663335e-23-7.36528394e-24j]
 [-1.47857217e-23+7.46938894e-24j]
 [-1.09976247e-23+1.23538756e-23j]
 [-2.05239329e-25-1.65131196e-23j]
 [-1.47892885e-23-7.29136603e-24j]
 [ 8.90758806e-24-1.38458065e-23j]
 [-1.55398380e-23-5.36021394e-24j]
 [-4.16950372e-24-1.58746097e-23j]
 [-6.06560706e-24+1.52239448e-23j]
 [-1.01999812e-23+1.27943386e-23j]
 [ 9.60587055e-24-1.32151102e-23j]
 [ 4.02524800e-24-1.58078766e-23j]
 [ 7.24329879e-24+1.45879548e-23j]
 [ 1.62195237e-23+1.17710988e-24j]
 [-4.52140264e-24+1.55949573e-23j]
 [ 1.59727390e-23+2.77616984e-24j]
 [ 4.06961719e-24+1.56673531e-23j]
 [ 8.83097849e-24-1.35364790e-23j]
 [ 1.43934279e-23-7.29718176e-24j]
 [-1.56094167e-23+3.99567158e-24j]
 [-1.52033891e-23+5.26102179e-24j]
 [ 1.21491014e-23-1.05083438e-23

In [8]:
FisherMatrsNet = myNet.FisherMatr(events, use_lensing=True)
FisherMatrsNet

Computing Fisher for L1...
Computing derivatives...
Computing Fisher for H1...
Computing derivatives...
Computing Fisher for Virgo...
Computing derivatives...
Done.


array([[[ 2.75391218e+01],
        [-6.63510120e+03],
        [-1.26456648e+01],
        [ 3.92378219e+01],
        [-4.96276984e+01],
        [-5.70679084e+00],
        [-4.56596515e+00],
        [ 2.88627910e+03],
        [-1.83462551e+01],
        [-2.51406302e+03],
        [-1.56276402e+03],
        [-2.97441546e-01],
        [ 3.49709755e-03]],

       [[-6.63510120e+03],
        [ 5.38052196e+06],
        [-9.98102999e+01],
        [-5.65812225e+04],
        [ 7.33215061e+04],
        [ 4.13752568e+03],
        [ 1.90087398e+04],
        [-9.72251792e+06],
        [ 2.81827934e+04],
        [ 2.50568632e+06],
        [ 1.64049853e+06],
        [ 5.92549316e+01],
        [-6.54968577e+00]],

       [[-1.26456648e+01],
        [-9.98102999e+01],
        [ 9.40294137e+02],
        [ 1.05714413e+03],
        [ 7.45594330e+02],
        [ 2.76253831e+02],
        [ 1.13347173e+02],
        [ 5.86726602e+01],
        [-1.68417167e+01],
        [-3.72773875e+01],
        [-2.17587067e+01

In [9]:
FisherMatrsNet_nolens = myNet.FisherMatr(events)
FisherMatrsNet_nolens

Computing Fisher for L1...
Computing derivatives...
Computing Fisher for H1...
Computing derivatives...
Computing Fisher for Virgo...
Computing derivatives...
Done.


array([[[ 9.51731309e+00],
        [-2.08691201e+03],
        [-3.22935664e+00],
        [-1.65700428e+01],
        [-2.03170663e+01],
        [ 9.10541945e+00],
        [-1.83892030e+01],
        [ 8.87491164e+02],
        [-1.10991445e+01],
        [-7.83160887e+02],
        [-4.86459403e+02]],

       [[-2.08691201e+03],
        [ 1.43359364e+06],
        [ 1.16643781e-13],
        [ 3.04023403e+03],
        [ 2.26987972e+04],
        [-5.78157801e+03],
        [ 1.53470508e+04],
        [-2.50001245e+06],
        [ 1.41376225e+04],
        [ 6.60846431e+05],
        [ 4.31839977e+05]],

       [[-3.22935664e+00],
        [ 1.16643781e-13],
        [ 2.42201748e+02],
        [ 2.75925270e+02],
        [ 1.98913471e+02],
        [ 1.39667599e+02],
        [ 6.46261672e+01],
        [-1.44653958e-02],
        [ 3.01317913e-16],
        [-5.93006128e-15],
        [-6.19076887e-15]],

       [[-1.65700428e+01],
        [ 3.04023403e+03],
        [ 2.75925270e+02],
        [ 1.37244379e+

In [10]:
Cov, ie = fTools.CovMatr(FisherMatrsNet)
Cov_nolens, ie_nolens = fTools.CovMatr(FisherMatrsNet_nolens)
ie, ie_nolens

(array([1.27271836e-06], dtype=float128), array([0.01115417], dtype=float128))

In [11]:
print((np.diag(Cov[:,:,0])))
print(np.sqrt(np.diag(Cov_nolens[:,:,0])))

[2.13814568e+01 1.59378660e-01 4.03858345e-03 7.67185848e-04
 1.34366202e-03 1.96725089e-03 9.79759589e-03 2.80511943e-02
 1.04754456e-02 1.51392809e+02 3.44206333e+02 8.77440912e+01
 1.34095903e+04]
[3.73055618e+02 1.47405295e+02 4.97490852e+00 6.68042225e-02
 9.96231501e-02 5.65416934e-02 1.30076439e-01 2.41896481e+01
 3.48873146e+04 1.28557211e+03 3.45759617e+03]
